AWSRegion: "ca-central-1"
DBHost: 192.168.86.24
DBName: ""
DBPassword: ""
DBUser: ""
HSTNumber: ""
LogoURI: "https://s3.amazonaws.com/ca.universalwindows/pdf/UniversalLogo.jpg"
DocAuthor: "Universal Windows"
S3Bucket: "ca-universalwindows"
SsmPath: "univsales-wrksht-pdf"
Stage: "prod"